// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';


const SUPABASE_URL = "https://boynjyevftdodqnujkdn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJveW5qeWV2ZnRkb2RxbnVqa2RuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0MTAzOTksImV4cCI6MjA3MDk4NjM5OX0.1o1RyHJjvj_G7b8fc5lRm55c1Z4k68wYjFBya4q_u-E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});